### ISSUE TITLE
Add link to official API

### ISSUE THREAD

**Issue by jebos** [SonnenladenGmbH/APsystems-EZ1-API#1]
Great work! 

It would be nice to also have a link to the official API Documentation (if there is one) in the Readme.

Are there any rate limits? How fast /slow can you set and query values?

**Comment by tacker66** [comment]
Link to official API: https://file.apsystemsema.com:8083/apsystems/apeasypower/resource/APsystems%20EZ1%20Local%20API%20User%20Manual.pdf

**Comment by SonnenladenGmbH** [comment]
@tacker66 thank you! I just added the latest document we received to this repo and the README.md. We will keep the document up-to-date when we will receive updated docs from APsystems from now on.

[assets/apsystems-documentation/APsystems EZ1 Local API - Documentation.pdf](https://github.com/SonnenladenGmbH/APsystems-EZ1-API/blob/main/assets/apsystems-documentation/APsystems%20EZ1%20Local%20API%20-%20Documentation.pdf)
