### ISSUE TITLE
EZ1-H

### ISSUE THREAD

**Issue by FlyingEagle** [SonnenladenGmbH/APsystems-EZ1-API#15]
### What happened?

Is this also usable for EZ1-___H____?

### Your python version

0

### Your OS inlcuding your version

0

**Comment by mawoka-myblock** [comment]
Can't test it but I suppose yes as it's using the same app and only has more power

**Comment by FlyingEagle** [comment]
ok, thx

**Comment by SonnenladenGmbH** [comment]
@FlyingEagle the EZ1-H will be compatible with the whole EZ1-Series of devices.
We'll receive a EZ1-H unit soon and do proper testing to confirm compatibility.
