### ISSUE TITLE
Feature request: Disable bluetooth by local api

### ISSUE THREAD

**Issue by DirkBaumeister** [SonnenladenGmbH/APsystems-EZ1-API#17]
As far as I have read online (Don't own this device yet) the inverter has an open bluetooth for direct connection while in local mode. There seems to be an option in cloud mode to disable bluetooth.

It would be amazing to have an api feature to disable bluetooth when in local mode.

Actually thats the only bummer for me right now that's stopping me from buying an EZ1. I'm currently choosing between hoymiles and APSystems and have a slight favor for the EZ1 because I don't like the CLEAR TEXT DTU transmission of the hoymiles inverters.
In my understanding I can set the EZ1 in a closed VLAN and just use it locally by API.

So an always open bluetooth is for me like the unencrypted DTU traffic of hoymiles (if not worse).

**So: Is it possible to disable bluetooth in local mode or any chance for this feature?**

Edit: Just saw that this might be a duplicate with https://github.com/SonnenladenGmbH/APsystems-EZ1-API/issues/4 so.. Any progress here? :)

**Comment by mawoka-myblock** [comment]
@SonnenladenGmbH, let your contacts play ;)

@DirkBaumeister This could take some time, maybe a month or even longer

**Comment by DirkBaumeister** [comment]
I'm not in a rush on this one :) But would be amazing actually if this could be implemented!

**Comment by mawoka-myblock** [comment]
I mean, I'd love to implement that, but that's not on my end, unfortunately...
