### ISSUE TITLE
Voltage information

### ISSUE THREAD

**Issue by silviokennecke** [SonnenladenGmbH/APsystems-EZ1-API#3]
In case the API already supports it, information about the current voltage for each string would be good.

I'm using the EZ1 with a battery and it would be great if I could get the battery voltage here. This way I would be able to replace the inaccurate voltage readings from my Shelly Uni with the ones from the micro inverter. I use the voltage in automations to prevent the battery being discharged below 10% and for a ruff estimation of the batteries charge state (this value decides when and how much power is used from the battery).

**Comment by SonnenladenGmbH** [comment]
@silviokennecke I will forward this to APsystems to see if they can implement it.
