### ISSUE TITLE
[Question]: does this library also work with APsystems EZ1D ? 

### ISSUE THREAD

**Issue by Ocramius** [SonnenladenGmbH/APsystems-EZ1-API#32]
### What happened?

Hey there!

Sorry in advance if I'm poking you, as an integrator that happened to do this work out of their own good will.

## Context - feel free to skip

I'm currently trying to understand whether I should embark in buying APsystems modules, and the EZ1 is a bit undersized for what I need to do (2*600W panels).

The EZ1D seems more suitable for this use-case (1800W capacity).

## Question: is EZ1D compatible?

Given the above, is the EZ1D usable with this module?

If you don't know, who would we ask?

Thanks in advance!

### Your python version

irrelevant

### Your OS inlcuding your version

irrelevant

**Comment by mawoka-myblock** [comment]
All of the EZ1 inverters are supported by this library though some docs are missing. Refer to the implementation in Home Assistant for reference.

**Comment by Ocramius** [comment]
wow, that was fast: thanks @mawoka-myblock!
