### ISSUE TITLE
[Bug]: Unexpected error fetching APSystems Data data

### ISSUE THREAD

**Issue by johanneswuerbach** [SonnenladenGmbH/APsystems-EZ1-API#33]
### What happened?

I'm using the [APsystems Home Assistant integration](https://www.home-assistant.io/integrations/apsystems) and while its working great most of the time 🎉 , I'm seeing quite a few `Unexpected error fetching APSystems Data data` errors in the Home Assistant logs (28 today) and the device is frequently becoming unavailable.

<img width="378" alt="image" src="https://github.com/user-attachments/assets/b5a2ee78-b509-4363-94e7-75de56c53f68">

Would it be possible to include additional details in those error messages to allow troubleshooting whether this is a connectivity error or something else?

### The python error

```shell
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/apsystems/coordinator.py", line 46, in _async_update_data
    output_data = await self.api.get_output_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/APsystemsEZ1/__init__.py", line 188, in get_output_data
    response = await self._request("getOutputData")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/APsystemsEZ1/__init__.py", line 96, in _request
    return await self._request(endpoint, retry=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/APsystemsEZ1/__init__.py", line 97, in _request
    raise InverterReturnedError
APsystemsEZ1.InverterReturnedError
```

### Your python version

3.12

### Your OS inlcuding your version

Home Assistant Core 2024.9.1 / OS 13.1

**Comment by mawoka-myblock** [comment]
This is not a connection issue. the `InverterReturnedError` is exactly what it sounds like. The inverter returns "Failed" upon a request without any obvious reasons. This means you can't do anything about that and it's not an issue with your setup.
