### ISSUE TITLE
Lifetime production counter reset to 0 when reaching 540,6 kWh

### ISSUE THREAD

**Issue by skrue** [SonnenladenGmbH/APsystems-EZ1-API#34]
Hi,
some days ago my inverter reached a lifetime production of 540,6 kWh on one of the strings and the counter was reset to 0. Four days later, the second string also reached 540,6 kWh and was also reset to 0.

The precise values of the last counter state recorded in the Home Assistant database before the reset are:
P1 = 540.60085 kWh
P2 = 540.59674 kWh

Here's a screenshot showing the issue, I forward all my sensor data from Home Assistant to InfluxDB and visualize it using Grafana.
![image](https://github.com/user-attachments/assets/154c0742-7720-466f-8d0c-990a6c87ccb0)

It looks the same in Home Assitant:
![image](https://github.com/user-attachments/assets/d1b9b814-740c-41a4-8342-f2d4ac8016db)

Any suggestions? I am still using the "old" custom component for HA integration, but to me it kind of feels like a problem with the inverter itself...

**Comment by mawoka-myblock** [comment]
Seems like a problem with the inverter itself, so there's nothing I can do, so feel free to get this resolved with APsystems directly. Good luck with that and, if you should find anything out, I'd love to be updated on this issue. But as it's not a problem with this library, I'll close this issue! But still thanks for bringing that up.

**Comment by xathon** [comment]
Did you ever hear back from APsystems on that?

**Comment by mawoka-myblock** [comment]
Not yet, unfortunately, but I'll keep trying.

**Comment by mawoka-myblock** [comment]
Have you reached out to the APsystems support yet as this is, as I've already said, an issue from APsystem's side and so far, I'm getting the same treatment as any other normal customer.
