### ISSUE TITLE
API support for EZHI

### ISSUE THREAD

**Issue by fsironman** [SonnenladenGmbH/APsystems-EZ1-API#38]
### What happened?

I couldn't find any information if the new model https://apsystems.com/ezhi/ will also be supported by this API. Ideally with additional endpoints for the battery management.

### Your python version

3

### Your OS inlcuding your version

Linux

**Comment by mawoka-myblock** [comment]
Probably not, as I don't have a testing device. If one would like to change that, I'd work on that. But until then, no, unfortunately.
